// benchmarks/color-picker/vue/components/App.vue
<template>
    <div class="colors">
        <h1>Choose your favorite color:</h1>
        <div class="colors">
            <ul v-if="colors.length">
                <li v-for="(color, i) in colors"
                    :class="['color', selectedColorIndex === i ? 'selected' : null]"
                    @click="handleColorClick(i)">
                    {{ color.name }}
                </li>
            </ul>
            <div v-else>
                No colors!
            </div>
        </div>
        <div>
            You chose:
            <div class="chosen-color">{{ colors[selectedColorIndex].name }}</div>
        </div>
    </div>
</template>

<script>
export default {
  props: ['colors', 'handleMount', 'handleUpdate'],
  mounted() {
    if (this.handleMount) {
      this.handleMount(this)
    }
    window.onMount()
  },
  updated() {
    if (this.handleUpdate) {
      this.handleUpdate(this)
    }
  },
  data: function() {
    return {
      selectedColorIndex: 0
    }
  },
  methods: {
    handleColorClick: function(colorIndex) {
      this.selectedColorIndex = colorIndex
    }
  }
}
</script>

// benchmarks/color-picker/react/components/App.jsx
const React = require("react");
const { useState, useEffect } = React;

function App({ onMount, colors }) {
  const [selectedColorIndex, setSelectedColorIndex] = useState(0);
  const selectedColor = colors[selectedColorIndex];
  useEffect(() => {
    onMount(setSelectedColorIndex);
    window.onMount();
  }, []);

  return (
    <div className="colors">
      <h1>Choose your favorite color:</h1>
      <div className="colors">{colors.length ? (
          <ul>
          {colors.map((color, i) => (
              <li
                className={"color" + (selectedColorIndex === i ? " selected" : "")}
                key={i}
                style={{
                  backgroundColor: color.hex
                }}
                onClick={() => setSelectedColorIndex(i)}
              >
                {color.name}
              </li>
            ))}
        </ul>
      ): <div>No colors!</div>}</div>
      <div>
        You chose:
        <div className="chosen-color">{selectedColor.name}</div>
      </div>
    </div>
  );
}

module.exports = App;
