// benchmarks/search-results/inferno/components/App.jsx
var Inferno = require('inferno');
var SearchResultsItem = require('./SearchResultsItem');
var Footer = require('./Footer');

module.exports = class extends Inferno.Component {
    componentDidMount() {
        window.onMount();
    }

    render() {
        var searchResultsData = this.props.searchResultsData;

        return (
            <div className="search-results">
                <div>
                    {searchResultsData.items.map(function(item, i) {
                        return <SearchResultsItem key={i} item={item}/>
                    })}
                </div>
                <Footer/>
            </div>
        );
    }
};

// benchmarks/search-results/vue/components/App.vue
<template>
  <div class="search-results">
    <div>
        <SearchResultsItem
          v-for="(item, i) in searchResultsData.items"
          :key="i"
          :item="item"
        />
    </div>
    <Footer/>
  </div>
</template>

<script>
import SearchResultsItem from './SearchResultsItem.vue'
import Footer from './Footer.vue'

export default {
  props: ['searchResultsData']
}
</script>
