// benchmarks/search-results/react/components/SearchResultsItem.jsx
var React = require('react');

module.exports = class extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            purchased: false,
            item: this.props.item
        };

        this.handleBuyButtonClick = this.handleBuyButtonClick.bind(this);
    }

    componentWillReceiveProps(props) {
        this.setState({
            purchased: false
        });
    }

    handleBuyButtonClick() {
        this.setState({ 'purchased': true });
    }

    render() {
        var item = this.props.item;
        var style = { backgroundColor: this.state.purchased ? '#f1c40f' : ''};

        return (
            <div className="search-results-item" style={style}>
                <h2>{item.title}</h2>

                <div className="lvpic pic img left">
            		<div className="lvpicinner full-width picW">
                        <a href={"/buy/" + item.id} className="img imgWr2">
            			     <img src={item.image} alt={item.title}/>
            			</a>
            		</div>
                </div>

                <span className="price">{item.price}</span>

                {this.state.purchased ?
                   <div className="purchased">Purchased!</div> :
                   <button className="buy-now" type="button" onClick={this.handleBuyButtonClick}>
                       Buy now!
                   </button>
                }

            </div>
        );
    }
};

// benchmarks/search-results/vue/components/SearchResultsItem.vue
<template>
    <div class="search-results-item"
         :style="{ backgroundColor: purchased ? '#f1c40f' : ''}">
        <h2>{{ item.title }}</h2>

        <div class="lvpic pic img left">
        <div class="lvpicinner full-width picW">
            <a :href="'/buy/' + item.id" class="img imgWr2">
               <img :src="item.image" alt="item.title">
            </a>
        </div>
        </div>

        <span class="price">{{ item.price }}</span>

        <div v-if="purchased" class="purchased">Purchased!</div>
        <button v-else class="buy-now" type="button" @click="handleBuyButtonClick">
            Buy now!
        </button>

    </div>
</template>

<script>
export default {
    props: ['item'],
    data () {
      return { purchased: false }
    },
    methods: {
        handleBuyButtonClick: function(instance) {
            this.purchased = true;
        }
    }
}
</script>
